language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121

script:
  # Restore, build and run
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet bin\Release\netcoreapp1.0\CSharp-PVRTCgen.dll -test > out.pvr
  - md5sum out.pvr